#
# This document contains settings for this blog, you can edit it to personalize your blog，
#

# Your blog name, please replace "LOFFER" with the blog name you want. The following modifications can be processed similarly
# Note that "name: LOFFER", the space after the colon cannot be omitted.
# The text after the pound sign is an explanatory document and will not be read by the program.
name: MAMOKIN
# Description / signature
description: Stuff & Things

#
# The following settings are optional
#

# URL of your blog logo image, the recommended size is no more than 300px × 300px
avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png

# URL of your favicon (appears on the browser tab) image, it is recommended to use a smaller (64px × 64px) image
favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# Buttons in the menu
navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

# Articles per page
paginate: 13

# Distinct markup for article introduction
excerpt_separator: <!-- more -->

# Your social network links, they will appear as icons in the footer of your website, optional
footer-links: 
  weibo: #请输入你的微博个性域名 [Please enter your Weibo personalized domain name] https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: m.seaward@mamok.in
  facebook: https://facebook.com/mamokin #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: https://github.com/mamokin #https://github.com/<>
  instagram: http://instagram.com/mamokin #https://instagram.com/<>
  linkedin: https://www.linkedin.com/in/mamokinmedia/ #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #Just fill in any RSS and use it
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: https://twitter.com/_Mamokin # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# Site footer text
footer-text: Copyright (c) 2019 Mamokin

# Comments, please note, please do not add multiple different comment areas at the same time

# Enter Disqus shortname to add a comment area
disqus: blog-mamokin #shortname

# Enter Gitalk related settings to add a comment area
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

# Enter Google Analytics web tracking code
google_analytics:

# Enter the domain name of your website (if you did not add your own domain name,
# but you can directly omit the domain name assigned by GitHub pages)
url: blog.mamok.in

# Add the secondary domain name of your blog, generally your repository name
# If the URL of your blog is: (http://yourusername.github.io/repository-name)
# Then write "/ repository-name"
baseurl: #/blog


#
# !! None of the following settings need to be changed !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

